services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  api:
    build: 
      context: ../unificha-api
      dockerfile: Dockerfile
    container_name: unificha-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    ports:
      - "3000:3000"